[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
  { access = "read-write", path = "./deployments/31337/data" }, 
  { access = "read", path = "./out" }
]

[rpc_endpoints]
op = "${OPTIMISM_RPC_URL}"